# This is a basic workflow to help you get started with Actions

name: My-GitHubActions-Basics
env:
  RaUs_APP_Name    : "My_Flask"
  RaUs_PACKAGE_Name: "Flask-Deploy-File-${{ github.sha }}" 
on:
  push:
    branches: [ main ]
jobs:
  my_testing:
     runs-on: ubuntu-latest
     steps:
     - name: Print Hello Message in Testing
       run : echo " Hello World Testing Job"
       
     - name: Execute few commands 
       run : |
         echo "Hello Message1"
         echo "Hello Message1"
         echo "Application Name : ${{ env.RaUs_APP_Name }}" 
         
     - name: List Current Folder before checkout
       run : ls -al

     - name: Git clone my repo
       uses: actions/checkout@v1
         
     - name: List Current Folder after checkout
       run : ls -al
             
  my_deploy:
     runs-on: ubuntu-latest
     needs: [my_testing]
     env:
       VAR1: "This is a job level variable 1"
       VAR2: "This is a job level variable 2"
     steps:
     - name: Print Hello Message in Deploy 
       run : echo " Hello World Deploy Job"
     - name: Print Job variables
       run: |
         echo " Var1 of Job = ${{ env.VAR1 }}"
         echo " Var2 of Job = ${{ env.VAR2 }}"
         echo " Var3 of Step = $LOCAL_STEP_VAR"
       env:
         LOCAL_STEP_VAR: "This is a step local variables"
     - name: Deployment Package 
       run: echo "Deploy Package Name is ${{ env.RaUs_PACKAGE_Name }}"   
     - name: Check if AWS cli command exit in docker machine 
       run: aws --version
     - name: Check if ZIP app exist on docker machine 
       run: zip --version
       
