# This is a basic workflow to help you get started with Actions

name: My-GitHubActions-Basics
on:
  push:
    branches: [ main ]
jobs:
  my_testing:
     runs-on: ubuntu-latest
     steps:
     - name: Print Hello Message
       run : echo " Hello World Testing Job"
  my_deploy:
     runs-on: ubuntu-latest
     steps:
     - name: Print Hello Message
       run : echo " Hello World Deploy Job"
        
